### ISSUE TITLE
Memory requirements?

### ISSUE THREAD

**Issue by zslittlehelper** [InfiMM/mllm-hd#1]
Is there any info on memory requirements for infinimm-hd?
Quantization support? Can it be split onto two 3090's with diffusers to work?

**Comment by liuhaogeng** [comment]
> Is there any info on memory requirements for infinimm-hd? Quantization support? Can it be split onto two 3090's with diffusers to work?

For the 13B version, it needs at least 40g. For the 7B version, 32g may be enough. (inferencing); As for now, it doesn't support quantization. We have not tried to split the model onto two 3090, so we can not give you reference.
